title: GitHub PagesでJekyllの自動ビルドを使ってブログサイトを作るを元にブログを作ってみた。
description: githubでホームページを作ってみたい！
baseurl: "/blogtest"
url: "https://meimei092.github.io"
markdown: kramdown
plugins:
- jekyll-feed
defaults:
-

scope:
path: ""
type: "posts"
values:
layout: "post"
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
